name: TENEX
options:
  bundleIdPrefix: com.tenex
  deploymentTarget:
    iOS: 17.0
  
targets:
  TENEX:
    type: application
    platform: iOS
    sources:
      - path: Sources/TENEX
        includes:
          - "**/*.swift"
        excludes:
          - ".build/**"
          - "project.yml"
      - path: Sources/TENEX/Resources/Assets.xcassets
        buildPhase: resources
      - path: Sources/TENEX/Resources/LaunchScreen.storyboard
        buildPhase: resources
      - path: Sources/TENEX/Info.plist
        buildPhase: none
    dependencies:
      - package: NDKSwift
        product: NDKSwift
      - package: NDKSwift
        product: NDKSwiftUI
    settings:
      base:
        INFOPLIST_FILE: Sources/TENEX/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.tenex.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        
packages:
  NDKSwift:
    url: https://github.com/pablof7z/NDKSwift
    branch: master
    
